[project]
name = "pOCR"
version = "0.1.0"
description = "Preprocessor to extract text from hardsubbed videos for OCR."
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["numpy>=2.3.5", "pillow>=12.0.0", "pytimeconv>=0.0.2", "vsjetpack>=1.0.0"]

[dependency-groups]
dev = [
    "mypy==1.19",
 "mypy-extensions==1.1.0",
 "ruff==0.9.4",
 "typing-extensions==4.15.0",
]

[tool.mypy]
mypy_path = "./stubs"
follow_imports = "silent"

ignore_missing_imports = true

no_implicit_optional = true
strict_optional = true

disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true

warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_return_any = true
warn_unreachable = true

ignore_errors = false

allow_untyped_globals = false
allow_redefinition = false

[tool.ruff]
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = ["E", "F", "W", "I"]

[tool.ruff.format]
exclude = ["*.pyi"]
quote-style = "double"
indent-style = "space"
